version: '3.8'

services:
  # Serviço da Aplicação (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: ${APP_USER:-sail}
        uid: ${APP_UID:-1000}
    image: sigafi-contabilidade-image
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:1.21-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # Serviço de Cache/Fila (Redis)
  redis:
    image: redis:6.2-alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - laravel

  # Serviço do Worker
  worker:
    image: sigafi-contabilidade-image
    # container_name: laravel-worker
    restart: unless-stopped
    command: "php artisan queue:work --verbose --tries=3 --timeout=90"
    env_file:
      - .env
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge